site_name: Wavelink
copyright: Copyright &copy; 2019-Present PythonistaGuild
repo_url: https://github.com/PythonistaGuild/Wavelink
repo_name: PythonistaGuild/Wavelink

theme:
  name: "material"
  palette:
    scheme: pythonista
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.share
  icon:
    annotation: material/chevron-right-circle
    repo: fontawesome/brands/github
  logo: assets/new_logo_trimmed.png
  font:
    text: Assistant

plugins:
  - tags
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: docs/templates
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
          - https://discordpy.readthedocs.io/en/stable/objects.inv
          - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            inherited_members: true
            group_by_category: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_section_style: "list"

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: _pages/getting-started/installing.md
    #- Quickstart: _pages/getting-started/quickstart.md
    #- Examples: _pages/getting-started/examples.md
  - References:
    # - Player: _pages/references/player.md
    # - AutoPlayMode: _pages/references/enums.md
      - Enums: _pages/references/enums.md

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/RAKc3HF
    - icon: fontawesome/brands/github
      link: https://github.com/PythonistaGuild/Wavelink